version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.17
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout

      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: go get -v -t -d ./...
      - run: ./cc-test-reporter before-build
      - run: go test -coverprofile=./c.out -race ./...
      - run: ./cc-test-reporter after-build -p $(go list -m) --exit-code $?
